# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
env:
  # can be replace crossplatform issue
  bash: C:\PROGRA~1\Git\bin\bash.exe --login -c --
  get : curl -Ls https://raw.githubusercontent.com/linitsh/scripts/main

includes:
  test: ./test.tasks.yml 

tasks:
  default: task --list-all
  
  push:
  - git add .
  - git commit -m "{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}Updated{{end}}"
  - git push

  test:
    - task: test:bash
    - task: test:bash-node
    - task: test:node

  get: $bash "$( $get/bash/test/test.sh )" -- -u name -a 33
