# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
env:
  # can be replace crossplatform issue
  bash: bash --login -c --
  # bash: C:\PROGRA~1\Git\bin\bash.exe --login -c --
  pwsh: powershell -command
  get : curl -Ls https://raw.githubusercontent.com/linitsh/scripts/main/remote
  node: node --input-type=module -e

includes:
  test: 
    taskfile: ./test.tasks.yml
    internal: true 
  env:
    taskfile: ./remote/tasks/settings/taskfile.env.yml
    internal: true
tasks:
  default: task --list-all
  
  push:
  - git add .
  - git commit -m "{{ .CLI_ARGS | default "Updated" }}"
  - git push

  test:
    internal: true
    cmds:
    - task: test:bash
    - task: test:bash-node
    - task: test:node

  get:
    internal: true
    cmds: 
    - $node "$( $get/node/npm/show.mjs )"
