# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
version: '3'
includes:
  shared: https://raw.githubusercontent.com/linitsh/scripts/main/shared.yml
  testy : ./remote/tasks/test/test-shared.yml

tasks:
  default: task --list-all
  
  push:
  - git add .
  - git commit -m "{{ .CLI_ARGS | default "Updated" }}"
  - git push

  test:
    internal: true
    cmds:
    - task: test:bash
    - task: test:bash-node
    - task: test:node

  get:
    internal: true
    cmds: 
    - $node "$( $get/node/npm/show.mjs )"

  all:
    - task: testy:hello